# Generated by Django 5.1.6 on 2025-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.CharField(blank=True, max_length=20, null=True)),
                ('char_id', models.CharField(blank=True, max_length=4, null=True)),
                ('char_txt', models.CharField(blank=True, max_length=4, null=True)),
                ('old_consonant', models.CharField(blank=True, max_length=20, null=True)),
                ('old_vowel', models.CharField(blank=True, max_length=20, null=True)),
                ('old_tone', models.CharField(blank=True, max_length=20, null=True)),
                ('young_consonant', models.CharField(blank=True, max_length=20, null=True)),
                ('young_vowel', models.CharField(blank=True, max_length=20, null=True)),
                ('young_tone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'yubao_mono',
            },
        ),
        migrations.CreateModel(
            name='MonoRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.CharField(blank=True, max_length=20, null=True)),
                ('char_id', models.CharField(blank=True, max_length=4, null=True)),
                ('char_txt', models.CharField(blank=True, max_length=4, null=True)),
                ('person', models.CharField(blank=True, max_length=20, null=True)),
                ('script', models.CharField(blank=True, max_length=200, null=True)),
                ('script_bk', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'yubao_mono_raw',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('firstLevelid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('filepath', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=1500, null=True)),
                ('population', models.CharField(blank=True, max_length=255, null=True)),
                ('nation', models.TextField(blank=True, null=True)),
                ('minorityInfo', models.TextField(blank=True, null=True)),
                ('dialectInfo', models.TextField(blank=True, null=True)),
                ('operaInfo', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('slice', models.CharField(blank=True, max_length=50, null=True)),
                ('slices', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'yubao_point',
            },
        ),
    ]
