# Generated by Django 5.1.6 on 2025-09-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yubao', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monoraw',
            index=models.Index(fields=['point', 'char_id'], name='idx_mono_raw_point_char'),
        ),
        migrations.AddConstraint(
            model_name='mono',
            constraint=models.UniqueConstraint(fields=('point', 'char_id'), name='uniq_mono_point_char'),
        ),
    ]
