# Generated by Django 5.1.6 on 2025-02-08 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuanZhu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('zitou', models.CharField(blank=True, max_length=20, null=True, verbose_name='字头')),
                ('chongwen', models.CharField(blank=True, max_length=20, null=True, verbose_name='重文')),
                ('zhengwen_zhushi', models.TextField(blank=True, null=True, verbose_name='正文注释')),
                ('bushou', models.CharField(blank=True, max_length=20, null=True, verbose_name='部首')),
                ('juan', models.CharField(blank=True, max_length=20, null=True, verbose_name='卷')),
            ],
            options={
                'verbose_name': '段注',
                'verbose_name_plural': '段注',
            },
        ),
        migrations.CreateModel(
            name='Gujinzi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('chuxian_zitou', models.CharField(blank=True, max_length=20, null=True, verbose_name='初选字头')),
                ('miaoshu', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('guzi_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='古字ID')),
                ('jinzi_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='今字ID')),
                ('duanzhu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '谐声声符',
                'verbose_name_plural': '谐声声符',
            },
        ),
        migrations.CreateModel(
            name='Guyunbu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('zitou', models.CharField(blank=True, max_length=20, null=True, verbose_name='字头')),
                ('yunbu', models.CharField(blank=True, max_length=20, null=True, verbose_name='韵部')),
                ('yunlei', models.CharField(blank=True, max_length=20, null=True, verbose_name='韵类')),
                ('duanzhu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '古韵部',
                'verbose_name_plural': '古韵部',
            },
        ),
        migrations.CreateModel(
            name='SwDu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('du_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('zitou', models.CharField(blank=True, max_length=20, null=True, verbose_name='字头')),
                ('zhushi', models.TextField(blank=True, null=True, verbose_name='注释')),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('duanzhu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '说文解字读',
                'verbose_name_plural': '说文解字读',
            },
        ),
        migrations.CreateModel(
            name='Xiesheng',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xieshengzi', models.CharField(blank=True, max_length=20, null=True, verbose_name='谐声字')),
                ('shengfu', models.CharField(blank=True, max_length=20, null=True, verbose_name='声符')),
                ('shengfu_duanzhuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shengfu_duanzhuID', to='manuscript.duanzhu', verbose_name='声符ID')),
                ('xieshengzi_duanzhuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xieshengzi_duanzhuID', to='manuscript.duanzhu', verbose_name='谐声字ID')),
            ],
            options={
                'verbose_name': '谐声声符',
                'verbose_name_plural': '谐声声符',
            },
        ),
    ]
