# Generated by Django 5.1.6 on 2025-02-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gujinzi',
            name='duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID'),
        ),
        migrations.AlterField(
            model_name='guyunbu',
            name='duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID'),
        ),
        migrations.AlterField(
            model_name='swdu',
            name='duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID'),
        ),
        migrations.AlterField(
            model_name='xiesheng',
            name='shengfu_duanzhuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shengfu_duanzhuID', to='manuscript.duanzhu', verbose_name='声符ID'),
        ),
        migrations.AlterField(
            model_name='xiesheng',
            name='xieshengzi_duanzhuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xieshengzi_duanzhuID', to='manuscript.duanzhu', verbose_name='谐声字ID'),
        ),
    ]
