# Generated by Django 5.1.6 on 2025-02-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0002_alter_gujinzi_duanzhu_alter_guyunbu_duanzhu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xiesheng',
            old_name='shengfu_duanzhuID',
            new_name='shengfu_duanzhu',
        ),
        migrations.RenameField(
            model_name='xiesheng',
            old_name='xieshengzi_duanzhuID',
            new_name='xieshengzi_duanzhu',
        ),
    ]
