# Generated by Django 5.1.6 on 2025-02-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0003_rename_shengfu_duanzhuid_xiesheng_shengfu_duanzhu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiesheng',
            name='shengfu_duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shengfu_duanzhu', to='manuscript.duanzhu', verbose_name='声符ID'),
        ),
        migrations.AlterField(
            model_name='xiesheng',
            name='xieshengzi_duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xieshengzi_duanzhu', to='manuscript.duanzhu', verbose_name='谐声字ID'),
        ),
    ]
