# Generated by Django 5.1.6 on 2025-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0004_alter_xiesheng_shengfu_duanzhu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duanzhu',
            name='duanzhu_bianhao',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='编号'),
        ),
    ]
