# Generated by Django 5.1.6 on 2025-02-18 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0005_alter_duanzhu_duanzhu_bianhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gouyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('gouyi1', models.TextField(blank=True, null=True, verbose_name='构意1')),
                ('gouyi2', models.TextField(blank=True, null=True, verbose_name='构意2')),
                ('gouyi3', models.TextField(blank=True, null=True, verbose_name='构意3')),
                ('shengfugouyi', models.TextField(blank=True, null=True, verbose_name='声符构意')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '构意阐释',
                'verbose_name_plural': '构意阐释',
            },
        ),
    ]
