# Generated by Django 5.1.6 on 2025-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0006_gouyi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gujinzi',
            options={'verbose_name': '古今字', 'verbose_name_plural': '古今字'},
        ),
        migrations.AddField(
            model_name='duanzhu',
            name='swxz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='说文小篆'),
        ),
    ]
