# Generated by Django 5.1.6 on 2025-03-18 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0007_alter_gujinzi_options_duanzhu_swxz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yinshu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idx', models.CharField(blank=True, max_length=20, null=True, verbose_name='idx')),
                ('book', models.TextField(blank=True, null=True, verbose_name='书名')),
                ('chapter', models.TextField(blank=True, null=True, verbose_name='章节')),
                ('content', models.TextField(blank=True, null=True, verbose_name='原文')),
                ('yiwen', models.TextField(blank=True, null=True, verbose_name='yiwen')),
                ('duanzhu_bianhaos', models.TextField(blank=True, null=True, verbose_name='段注编号')),
            ],
            options={
                'verbose_name': '音义同',
                'verbose_name_plural': '音义同',
            },
        ),
        migrations.CreateModel(
            name='Zhishimulu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(blank=True, null=True, verbose_name='目录名')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父级id')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='目录层级')),
            ],
            options={
                'verbose_name': '知识目录',
                'verbose_name_plural': '知识目录',
            },
        ),
        migrations.AddField(
            model_name='duanzhu',
            name='img_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径'),
        ),
        migrations.CreateModel(
            name='Yinyitong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('object1', models.TextField(blank=True, null=True, verbose_name='对象1')),
                ('object1_duanzhu_bianhao', models.TextField(blank=True, null=True, verbose_name='对象1段注编号')),
                ('object2', models.TextField(blank=True, null=True, verbose_name='对象2')),
                ('object2_duanzhu_bianhao', models.TextField(blank=True, null=True, verbose_name='对象2段注编号')),
                ('duanshianyu', models.TextField(blank=True, null=True, verbose_name='段氏按语')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '音义同',
                'verbose_name_plural': '音义同',
            },
        ),
    ]
