# Generated by Django 5.1.6 on 2025-03-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0008_yinshu_zhishimulu_duanzhu_img_path_yinyitong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yinshu',
            options={'verbose_name': '引书', 'verbose_name_plural': '引书'},
        ),
    ]
