# Generated by Django 5.1.6 on 2025-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0009_alter_yinshu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhishimulu',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='请求url'),
        ),
    ]
