# Generated by Django 5.1.6 on 2025-04-04 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0010_zhishimulu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jiajie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('jiajiezhuwen', models.TextField(blank=True, null=True, verbose_name='假借注文')),
                ('jiajiebiaoqian', models.TextField(blank=True, null=True, verbose_name='假借标签')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '假借',
                'verbose_name_plural': '假借',
            },
        ),
        migrations.CreateModel(
            name='Liushu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('liushu', models.TextField(blank=True, null=True, verbose_name='六书')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '六书',
                'verbose_name_plural': '六书',
            },
        ),
        migrations.CreateModel(
            name='Tongzi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('tongzizhuwen', models.TextField(blank=True, null=True, verbose_name='同字注文')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '同字',
                'verbose_name_plural': '同字',
            },
        ),
        migrations.CreateModel(
            name='Xingfeizi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('pipeizifuchuan', models.TextField(blank=True, null=True, verbose_name='匹配字符串')),
                ('xingzi', models.TextField(blank=True, null=True, verbose_name='行字')),
                ('feizi', models.TextField(blank=True, null=True, verbose_name='废字')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '行废字',
                'verbose_name_plural': '行废字',
            },
        ),
        migrations.CreateModel(
            name='Zhuanzhu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('zhuanzhu', models.TextField(blank=True, null=True, verbose_name='转注')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '转注',
                'verbose_name_plural': '转注',
            },
        ),
    ]
