# Generated by Django 5.1.6 on 2025-04-05 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0011_jiajie_liushu_tongzi_xingfeizi_zhuanzhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('benyi_1', models.TextField(blank=True, null=True, verbose_name='本义1')),
                ('benyi_2', models.TextField(blank=True, null=True, verbose_name='本义2')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '本义',
                'verbose_name_plural': '本义',
            },
        ),
        migrations.CreateModel(
            name='Gujinyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('shuojie', models.TextField(blank=True, null=True, verbose_name='说解')),
                ('biaoqian', models.TextField(blank=True, null=True, verbose_name='标签')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '古义今义',
                'verbose_name_plural': '古义今义',
            },
        ),
        migrations.CreateModel(
            name='Huxun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('shuojie', models.TextField(blank=True, null=True, verbose_name='说解')),
                ('huxunzu', models.TextField(blank=True, null=True, verbose_name='互训组')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '互训',
                'verbose_name_plural': '互训',
            },
        ),
        migrations.CreateModel(
            name='Lianmianci',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('zitou', models.TextField(blank=True, null=True, verbose_name='字头')),
                ('lianmianci', models.TextField(blank=True, null=True, verbose_name='联绵词')),
                ('ciyileibie', models.TextField(blank=True, null=True, verbose_name='词义类别')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '联绵词',
                'verbose_name_plural': '联绵词',
            },
        ),
        migrations.CreateModel(
            name='Yinshen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('yinshen', models.TextField(blank=True, null=True, verbose_name='引申')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '引申义',
                'verbose_name_plural': '引申义',
            },
        ),
        migrations.CreateModel(
            name='Zhiyan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('zhiyanshuojie', models.TextField(blank=True, null=True, verbose_name='之言说解')),
                ('duixiang', models.TextField(blank=True, null=True, verbose_name='对象')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '之言',
                'verbose_name_plural': '之言',
            },
        ),
    ]
