# Generated by Django 5.1.6 on 2025-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0012_benyi_gujinyi_huxun_lianmianci_yinshen_zhiyan'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhishimulu',
            name='shuyuxingshi',
            field=models.TextField(blank=True, null=True, verbose_name='术语形式'),
        ),
        migrations.AddField(
            model_name='zhishimulu',
            name='yanjiutuijie',
            field=models.TextField(blank=True, null=True, verbose_name='研究推介'),
        ),
        migrations.AddField(
            model_name='zhishimulu',
            name='zhishishuoming',
            field=models.TextField(blank=True, null=True, verbose_name='知识说明'),
        ),
    ]
