# Generated by Django 5.1.6 on 2025-04-12 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0013_zhishimulu_shuyuxingshi_zhishimulu_yanjiutuijie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benzuo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '本作',
                'verbose_name_plural': '本作',
            },
        ),
        migrations.CreateModel(
            name='Bieyiyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '别一义',
                'verbose_name_plural': '别一义',
            },
        ),
        migrations.CreateModel(
            name='Dieyun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '叠韵',
                'verbose_name_plural': '叠韵',
            },
        ),
        migrations.CreateModel(
            name='Duotuo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content1', models.TextField(blank=True, null=True, verbose_name='匹配内容1')),
                ('match_content2', models.TextField(blank=True, null=True, verbose_name='匹配内容2')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '夺',
                'verbose_name_plural': '夺',
            },
        ),
        migrations.CreateModel(
            name='Ezi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '讹字',
                'verbose_name_plural': '讹字',
            },
        ),
        migrations.CreateModel(
            name='Fangsu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '方言俗语',
                'verbose_name_plural': '方言俗语',
            },
        ),
        migrations.CreateModel(
            name='Fanxun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '反训',
                'verbose_name_plural': '反训',
            },
        ),
        migrations.CreateModel(
            name='Feishi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '非是',
                'verbose_name_plural': '非是',
            },
        ),
        migrations.CreateModel(
            name='Guheyun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '古合韵',
                'verbose_name_plural': '古合韵',
            },
        ),
        migrations.CreateModel(
            name='Guyin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '古音',
                'verbose_name_plural': '古音',
            },
        ),
        migrations.CreateModel(
            name='Guyu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '古语',
                'verbose_name_plural': '古语',
            },
        ),
        migrations.CreateModel(
            name='Hujian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '互见',
                'verbose_name_plural': '互见',
            },
        ),
        migrations.CreateModel(
            name='Hunyanxiyan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('duanzhushuyu', models.TextField(blank=True, null=True, verbose_name='段注术语')),
                ('xibianduixiang', models.TextField(blank=True, null=True, verbose_name='辨析对象')),
                ('obj1_duanzhu_id', models.TextField(blank=True, null=True, verbose_name='对象1_duanzhu_id')),
                ('obj2_duanzhu_id', models.TextField(blank=True, null=True, verbose_name='对象2_duanzhu_id')),
                ('obj3_duanzhu_id', models.TextField(blank=True, null=True, verbose_name='对象3_duanzhu_id')),
                ('obj4_duanzhu_id', models.TextField(blank=True, null=True, verbose_name='对象4_duanzhu_id')),
                ('obj5_duanzhu_id', models.TextField(blank=True, null=True, verbose_name='对象5_duanzhu_id')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '浑言析言',
                'verbose_name_plural': '浑言析言',
            },
        ),
        migrations.CreateModel(
            name='Jinyin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '今音',
                'verbose_name_plural': '今音',
            },
        ),
        migrations.CreateModel(
            name='Shan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '删',
                'verbose_name_plural': '删',
            },
        ),
        migrations.CreateModel(
            name='Shengfushiyuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '声符示源',
                'verbose_name_plural': '声符示源',
            },
        ),
        migrations.CreateModel(
            name='Shuangsheng',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('obj1', models.TextField(blank=True, null=True, verbose_name='双声对象1')),
                ('obj2', models.TextField(blank=True, null=True, verbose_name='双声对象2')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '双声',
                'verbose_name_plural': '双声',
            },
        ),
        migrations.CreateModel(
            name='Shuozi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '说字',
                'verbose_name_plural': '说字',
            },
        ),
        migrations.CreateModel(
            name='Suiwen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '随文',
                'verbose_name_plural': '随文',
            },
        ),
        migrations.CreateModel(
            name='Suzi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '俗字',
                'verbose_name_plural': '俗字',
            },
        ),
        migrations.CreateModel(
            name='Tongxun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '同训',
                'verbose_name_plural': '同训',
            },
        ),
        migrations.CreateModel(
            name='Tongyu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '通语',
                'verbose_name_plural': '通语',
            },
        ),
        migrations.CreateModel(
            name='Wanggai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '妄改',
                'verbose_name_plural': '妄改',
            },
        ),
        migrations.CreateModel(
            name='Yijinshigu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '以今释古',
                'verbose_name_plural': '以今释古',
            },
        ),
        migrations.CreateModel(
            name='Yinbian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '音变',
                'verbose_name_plural': '音变',
            },
        ),
        migrations.CreateModel(
            name='Yintongyiyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '音同义异',
                'verbose_name_plural': '音同义异',
            },
        ),
        migrations.CreateModel(
            name='Yinzhuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '音转',
                'verbose_name_plural': '音转',
            },
        ),
        migrations.CreateModel(
            name='Yiwen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '异文',
                'verbose_name_plural': '异文',
            },
        ),
        migrations.CreateModel(
            name='Yixiangzu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '义相足',
                'verbose_name_plural': '义相足',
            },
        ),
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('a', models.TextField(blank=True, null=True, verbose_name='A')),
                ('a_id', models.TextField(blank=True, null=True, verbose_name='A_id')),
                ('b', models.TextField(blank=True, null=True, verbose_name='B')),
                ('b_id', models.TextField(blank=True, null=True, verbose_name='B_id')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '犹',
                'verbose_name_plural': '犹',
            },
        ),
        migrations.CreateModel(
            name='Zheng',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '正',
                'verbose_name_plural': '正',
            },
        ),
        migrations.CreateModel(
            name='Zhuanyu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '转语',
                'verbose_name_plural': '转语',
            },
        ),
        migrations.CreateModel(
            name='Zuijin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '最近',
                'verbose_name_plural': '最近',
            },
        ),
    ]
