# Generated by Django 5.1.6 on 2025-05-08 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0014_benzuo_bieyiyi_dieyun_duotuo_ezi_fangsu_fanxun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xingfeiyi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('yixingyifeishuojie', models.TextField(blank=True, null=True, verbose_name='义行义废说解')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '行废义',
                'verbose_name_plural': '行废义',
            },
        ),
    ]
