# Generated by Django 5.1.6 on 2025-05-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0015_xingfeiyi'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanzhu',
            name='yema',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='页码'),
        ),
    ]
