# Generated by Django 5.1.6 on 2025-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0016_duanzhu_yema'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhishimulu',
            name='shuyuxingshi_jian',
            field=models.TextField(blank=True, null=True, verbose_name='术语形式-简体'),
        ),
    ]
