# Generated by Django 5.1.6 on 2025-06-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0017_zhishimulu_shuyuxingshi_jian'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanzhu',
            name='status',
            field=models.IntegerField(default=0, verbose_name='标注状态'),
        ),
        migrations.AddField(
            model_name='duanzhu',
            name='zhengwen_zhushi_bz',
            field=models.TextField(blank=True, null=True, verbose_name='正文注释标注'),
        ),
    ]
