# Generated by Django 5.1.6 on 2025-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0018_duanzhu_status_duanzhu_zhengwen_zhushi_bz'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanzhu',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='duanzhu',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='标注用户id'),
        ),
    ]
