# Generated by Django 5.1.6 on 2025-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0019_duanzhu_update_time_duanzhu_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhishimulu',
            name='shuxing',
            field=models.TextField(blank=True, null=True, verbose_name='属性'),
        ),
    ]
