# Generated by Django 5.1.6 on 2025-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0020_zhishimulu_shuxing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhishimulu',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
