# Generated by Django 5.1.6 on 2025-08-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0021_alter_zhishimulu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='liushu',
            name='zhishimiaoshu',
            field=models.TextField(blank=True, null=True, verbose_name='知识描述'),
        ),
        migrations.AlterField(
            model_name='liushu',
            name='duanzhu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liushus', to='manuscript.duanzhu', verbose_name='段注ID'),
        ),
    ]
