# Generated by Django 5.1.6 on 2025-08-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0022_liushu_zhishimiaoshu_alter_liushu_duanzhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAnnotate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_point', models.CharField(blank=True, max_length=20, null=True, verbose_name='知识点')),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('is_belong', models.IntegerField(blank=True, default=0, null=True, verbose_name='是否属于该知识点')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '知识点标注记录',
                'verbose_name_plural': '知识点标注记录',
            },
        ),
    ]
