# Generated by Django 5.1.6 on 2025-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0023_knowledgeannotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gouyi',
            name='match_content',
            field=models.TextField(blank=True, null=True, verbose_name='匹配内容'),
        ),
    ]
