# Generated by Django 5.1.6 on 2025-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0024_gouyi_match_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='benyi',
            name='match_content',
            field=models.TextField(blank=True, null=True, verbose_name='匹配内容'),
        ),
    ]
