# Generated by Django 5.1.6 on 2025-08-18 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0026_duotuo_match_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('object1', models.TextField(blank=True, null=True, verbose_name='对象1')),
                ('object1_duanzhu_bianhao', models.TextField(blank=True, null=True, verbose_name='对象1段注编号')),
                ('object2', models.TextField(blank=True, null=True, verbose_name='对象2')),
                ('object2_duanzhu_bianhao', models.TextField(blank=True, null=True, verbose_name='对象2段注编号')),
                ('miaoshu', models.TextField(blank=True, null=True, verbose_name='知识点描述')),
                ('knowledge', models.TextField(blank=True, null=True, verbose_name='知识点描述')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '多对象关系型知识点标注数据',
                'verbose_name_plural': '多对象关系型知识点标注数据',
            },
        ),
    ]
