# Generated by Django 5.1.6 on 2025-08-30 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0027_relationknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationknowledge',
            name='knowledge',
            field=models.TextField(blank=True, null=True, verbose_name='知识点'),
        ),
        migrations.CreateModel(
            name='SingleObjectKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duanzhu_bianhao', models.CharField(blank=True, max_length=20, null=True, verbose_name='段注编号')),
                ('match_content', models.TextField(blank=True, null=True, verbose_name='匹配内容')),
                ('knowledge', models.TextField(blank=True, null=True, verbose_name='知识点')),
                ('duanzhu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.duanzhu', verbose_name='段注ID')),
            ],
            options={
                'verbose_name': '单对象描述型知识点标注数据',
                'verbose_name_plural': '单对象描述型知识点标注数据',
            },
        ),
    ]
